/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_posts` VALUES
(1,1,"2017-11-26 05:12:50","2017-11-26 05:12:50","Welcome to WordPress. This is your first post. Edit or delete it, then start writing!","Hello world!","","publish","open","open","","hello-world","","","2017-11-26 05:12:50","2017-11-26 05:12:50","",0,"http://fictional-university.local/?p=1",0,"post","",1),
(2,1,"2017-11-26 05:12:50","2017-11-26 05:12:50","This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\n\n<blockquote>Hi there! I\'m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin\' caught in the rain.)</blockquote>\n\n...or something like this:\n\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\n\nAs a new WordPress user, you should go to <a href=\"http://fictional-university.local/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!","Sample Page","","publish","closed","open","","sample-page","","","2017-11-26 05:12:50","2017-11-26 05:12:50","",0,"http://fictional-university.local/?page_id=2",0,"page","",0),
(3,1,"2017-12-06 01:52:53","0000-00-00 00:00:00","","Auto Draft","","auto-draft","open","open","","","","","2017-12-06 01:52:53","0000-00-00 00:00:00","",0,"http://fictional-university.local/?p=3",0,"post","",0),
(4,1,"2017-12-07 03:10:15","2017-12-07 03:10:15","<p align=\"justify\">Lorem ipsum dolor sit amet, ac neque tristique bibendum dictum, sit et nulla magna. In vel sed quisque ac sed morbi. Congue tempor dolor, in congue dignissim, consectetuer erat magnis pretium urna. Risus fusce tristique justo feugiat. Augue non ac dignissim. A praesent ultricies integer, integer vehicula sapien, magnam purus varius consequat, ac pulvinar nullam integer fusce quisque. Tincidunt et nibh, officia morbi maecenas et sed dui elit, commodo in, feugiat eros lacus ipsum, tortor orci eget. Est mattis quis bibendum tincidunt, enim amet nullam quisque wisi parturient. Et pulvinar sit, porta sed semper, mi faucibus porta, praesent adipiscing wisi amet suspendisse, adipiscing praesent magna.</p>","Post 1","","publish","open","open","","post-1","","","2017-12-07 03:10:15","2017-12-07 03:10:15","",0,"http://fictional-university.local/?p=4",0,"post","",0),
(5,1,"2017-12-07 03:10:15","2017-12-07 03:10:15","<p align=\"justify\">Lorem ipsum dolor sit amet, ac neque tristique bibendum dictum, sit et nulla magna. In vel sed quisque ac sed morbi. Congue tempor dolor, in congue dignissim, consectetuer erat magnis pretium urna. Risus fusce tristique justo feugiat. Augue non ac dignissim. A praesent ultricies integer, integer vehicula sapien, magnam purus varius consequat, ac pulvinar nullam integer fusce quisque. Tincidunt et nibh, officia morbi maecenas et sed dui elit, commodo in, feugiat eros lacus ipsum, tortor orci eget. Est mattis quis bibendum tincidunt, enim amet nullam quisque wisi parturient. Et pulvinar sit, porta sed semper, mi faucibus porta, praesent adipiscing wisi amet suspendisse, adipiscing praesent magna.</p>","Post 1","","inherit","closed","closed","","4-revision-v1","","","2017-12-07 03:10:15","2017-12-07 03:10:15","",4,"http://fictional-university.local/4-revision-v1/",0,"revision","",0),
(6,1,"2017-12-07 03:10:39","2017-12-07 03:10:39","<p align=\"justify\">Arcu sollicitudin venenatis volutpat, pede lacus tellus, pellentesque odio lectus turpis at, sem ipsum purus, ut dapibus. Non sed dictum diam dolor enim, donec tellus, vitae turpis aliquam viverra praesent vulputate, orci lectus mi, lorem maecenas faucibus. Donec nec in quam, imperdiet sed etiam non tristique, nec nunc urna, sit scelerisque fusce, lacinia a est nisl. Et dapibus, blandit maecenas nunc vitae, mauris platea praesent odio maecenas sapien in, eu posuere urna, justo odio. Justo amet, praesent nulla turpis vulputate sem officia ac. Arcu nobis. Magna tincidunt ut. In pede. Consectetuer accumsan aenean, libero vitae veniam felis sit elit eget. Nisl malesuada bibendum ligula condimentum turpis orci. Ut urna.</p>","Post 2","","publish","open","open","","post-2","","","2017-12-07 03:10:39","2017-12-07 03:10:39","",0,"http://fictional-university.local/?p=6",0,"post","",0),
(7,1,"2017-12-07 03:10:39","2017-12-07 03:10:39","<p align=\"justify\">Arcu sollicitudin venenatis volutpat, pede lacus tellus, pellentesque odio lectus turpis at, sem ipsum purus, ut dapibus. Non sed dictum diam dolor enim, donec tellus, vitae turpis aliquam viverra praesent vulputate, orci lectus mi, lorem maecenas faucibus. Donec nec in quam, imperdiet sed etiam non tristique, nec nunc urna, sit scelerisque fusce, lacinia a est nisl. Et dapibus, blandit maecenas nunc vitae, mauris platea praesent odio maecenas sapien in, eu posuere urna, justo odio. Justo amet, praesent nulla turpis vulputate sem officia ac. Arcu nobis. Magna tincidunt ut. In pede. Consectetuer accumsan aenean, libero vitae veniam felis sit elit eget. Nisl malesuada bibendum ligula condimentum turpis orci. Ut urna.</p>","Post 2","","inherit","closed","closed","","6-revision-v1","","","2017-12-07 03:10:39","2017-12-07 03:10:39","",6,"http://fictional-university.local/6-revision-v1/",0,"revision","",0);
